name: MarcoLoguercio
favicon: null
layout_spectrum: 0.57223
title: Marco Loguercio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a0a0d'
    - '#ffffff'
    - '#bf5c23'
    - '#dfd2c2'
    - '#aa9c93'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose:
  - name: engagement
    item: null
    url: null
